import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  // index("routes/home.tsx"),
  route("login", "routes/auth.tsx"),
  // Portal de Pacientes - RUTAS SEPARADAS DEL DASHBOARD
  route('pacientes/laboratorio', 'routes/pacientes-laboratorio.tsx', [
    route('login', 'routes/pacientes-laboratorio-login.tsx'),
    route('mis-examenes', 'routes/pacientes-laboratorio-mis-examenes.tsx'),
    route('examen/:id', 'routes/pacientes-laboratorio-examen-detalle.tsx'),
  ]),
  // Dashboard del ERP - RUTAS PROTEGIDAS PARA STAFF/ADMIN
  route('/', 'routes/dashboard.tsx', [
    index('routes/home.tsx'),
    route('cuidados-en-casa', 'routes/cuidados-en-casa.tsx'),
    route('cuidados-en-casa/:patientId', 'routes/cuidados-en-casa-detalle.tsx'),
    route('pacientes', 'routes/pacientes.tsx'),
    route('pacientes/:id', 'routes/paciente-detalle.tsx'),
    route('personal', 'routes/personal.tsx'),
    route('personal/:category', 'routes/personal-category.tsx'),
    route('citas', 'routes/citas.tsx'),
    route('procedimientos', 'routes/procedimientos.tsx'),
    route('procedimientos/catalogo', 'routes/procedimientos-catalogo.tsx'),
    route('procedimientos/listado', 'routes/procedimientos-listado.tsx'),
    route('procedimientos/listado/:id', 'routes/procedimientos-detalle.tsx'),
    route('procedimientos/reportes', 'routes/procedimientos-reportes.tsx'),
    route('servicios', 'routes/servicios.tsx'),
    route('cotizaciones', 'routes/cotizaciones.tsx'),
    route('laboratorio', 'routes/laboratorio.tsx'),
    route('laboratorio/seleccionar', 'routes/laboratorio-seleccionar.tsx'),
    route('laboratorio/buscar', 'routes/laboratorio-buscar.tsx'),
    route('laboratorio/reportes', 'routes/laboratorio-reportes.tsx'),
    route('laboratorio/ordenes', 'routes/laboratorio-ordenes.tsx'),
    route('laboratorio/ordenes/:id', 'routes/laboratorio-orden-detalle.tsx'),
    route('enfermeria', 'routes/enfermeria.tsx'),
    route('enfermeria/valoracion-inicial', 'routes/enfermeria-valoracion.tsx'),
    route('enfermeria/signos-vitales', 'routes/enfermeria-signos-vitales.tsx'),
    route('enfermeria/evolucion', 'routes/enfermeria-evolucion.tsx'),
    route('enfermeria/eliminacion', 'routes/enfermeria-eliminacion.tsx'),
    route('enfermeria/valoraciones', 'routes/enfermeria-valoraciones.tsx'),
    route('inventario', 'routes/inventario.tsx'),
    route('facturacion', 'routes/facturacion.tsx'),
    route('reportes', 'routes/reportes.tsx'),
    route('emergencias', 'routes/emergencias.tsx'),
    route('configuracion', 'routes/configuracion.tsx'),
    route('mi-perfil', 'routes/mi-perfil.tsx'),
  ]),
] satisfies RouteConfig;
